# Generated by Django 5.1.1 on 2024-09-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FUser',
            fields=[
                ('id_f_user', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_famille', models.CharField(max_length=100)),
                ('coefficient', models.IntegerField()),
                ('remarques', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'f_user',
                'managed': False,
            },
        ),
    ]
